export { default as Login } from './Login'
export { default as Start } from './Start'
export { default as Form } from './Form'
export { default as Home } from './Home'
export { default as Artist } from './Artist'
export { default as Playlist } from '../components/Playlist'